run:
  skip-files:
    - "./models/.*.go"
linters:
  fast: true
  enable-all: true
  disable:
    - funlen
    - dupl
    - gocognit
    - gocyclo
    - maintidx
    - testpackage
    - gomnd
    - gci # よくわからん
    - gofumpt # よくわからん
    - gocritic # runするとエラーになる
issues:
  fix: true
