// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type Category struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Todos []*Todo `json:"todos"`
}

type CreateCategoryInput struct {
	Name string `json:"name"`
}

type CreateTodoInput struct {
	Content    string  `json:"content"`
	CategoryID *string `json:"categoryId,omitempty"`
}

type Todo struct {
	ID        string    `json:"id"`
	Content   string    `json:"content"`
	Category  *Category `json:"category,omitempty"`
	Done      bool      `json:"done"`
	CreatedAt int       `json:"createdAt"`
}

type UpdateCategoryInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UpdateTodoInput struct {
	ID         string  `json:"id"`
	Content    *string `json:"content,omitempty"`
	CategoryID *string `json:"categoryId,omitempty"`
	Done       *bool   `json:"done,omitempty"`
}
