// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type CreateCategoryInput struct {
	Name string `json:"name"`
}

type CreateTodoInput struct {
	Content    string  `json:"content"`
	CategoryID *string `json:"categoryId,omitempty"`
}

type UpdateCategoryInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UpdateTodoInput struct {
	ID         string  `json:"id"`
	Content    *string `json:"content,omitempty"`
	CategoryID *string `json:"categoryId,omitempty"`
	Done       *bool   `json:"done,omitempty"`
}
