name: Run CI/CD

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Download all modules
        run: go mod download

      - name: Run tests
        run: make test
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCLOUD_AUTH }}"

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Configure docker for artifact registry
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build
        run: |
          TAG=$(echo $GITHUB_REF | awk -F/ '{print $NF}')
          IMAGE_NAME=asia-northeast1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/cloud-run-source-deploy/${TAG}
          docker build --platform linux/amd64 -t ${IMAGE_NAME} .
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

      - name: Push
        run: docker push ${{ env.IMAGE_NAME }}

      - name: Deploy
        run: |-
          gcloud run deploy saas-sample-api \
            --project=${{ secrets.PROJECT_ID }} \
            --image=${IMAGE_NAME} \
            --region=asia-northeast1 \
            --service-account=${{ secrets.SERVICE_ACCOUNT }}
